# Generated by Django 4.2.4 on 2023-09-20 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, default=datetime.date(2023, 9, 21), max_length=300, verbose_name='نام در url'),
            preserve_default=False,
        ),
    ]
