# Generated by Django 4.2.4 on 2023-09-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_user_about_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='About_user',
            new_name='about_user',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile', verbose_name='تصویر آواتار'),
        ),
    ]
